In [1]:
import soccerdata as sd

fbref = sd.FBref(leagues="ENG-Premier League", seasons="2425")
stats = fbref.read_player_season_stats(stat_type="standard")
stats.head(20)

[07/06/26 15:55:29] INFO     No custom team name replacements found. You can configure these in       ]8;id=3479948;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=3479949;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_config.py#92\92]8;;\
                             /Users/jade/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=3479955;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=3479956;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_config.py#190\190]8;;\
                             /Users/jade/soccerdata/config/league_dict.json.

                    INFO     Saving cached data to /Users/jade/soccerdata/data/FBref                 ]8;id=3479963;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=3479964;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\

                                                        nation    pos age  \

league             season team    player
ENG-Premier League 2425   Arsenal Ben White                ENG     DF  26
                                  Bukayo Saka              ENG  FW,MF  22
                                  David Raya               ESP     GK  28
                                  Declan Rice              ENG     MF  25
                                  Ethan Nwaneri            ENG  FW,MF  17
                                  Gabriel Jesus            BRA     FW  27
                                  Gabriel Magalhães        BRA     DF  26
                                  Gabriel Martinelli       BRA  FW,MF  23
                                  Jakub Kiwior             POL     DF  24
                                  Jorginho                 ITA     MF  32
                                  Jurriën Timber           NED     DF  23
                                  Kai Havertz              GER     FW  25
                                  Kieran Tierney           SCO     DF  27
                                  Leandro Trossard         BEL     FW  29
                                  Martin Ødegaard          NOR     MF  25
                                  Mikel Merino             ESP  MF,FW  28
                                  Myles Lewis-Skelly       ENG     DF  17
                                  Nathan Butler-Oyedeji    ENG     FW  21
                                  Oleksandr Zinchenko      UKR  DF,MF  27
                                  Raheem Sterling          ENG  FW,MF  29

                                                         born Playing Time  \
                                                                        MP
league             season team    player
ENG-Premier League 2425   Arsenal Ben White              1997           17
                                  Bukayo Saka            2001           25
                                  David Raya             1995           38
                                  Declan Rice            1999           35
                                  Ethan Nwaneri          2007           26
                                  Gabriel Jesus          1997           17
                                  Gabriel Magalhães      1997           28
                                  Gabriel Martinelli     2001           33
                                  Jakub Kiwior           2000           17
                                  Jorginho               1991           15
                                  Jurriën Timber         2001           30
                                  Kai Havertz            1999           23
                                  Kieran Tierney         1997           13
                                  Leandro Trossard       1994           38
                                  Martin Ødegaard        1998           30
                                  Mikel Merino           1996           28
                                  Myles Lewis-Skelly     2006           23
                                  Nathan Butler-Oyedeji  2003            1
                                  Oleksandr Zinchenko    1996           15
                                  Raheem Sterling        1994           17

                                                                            \
                                                        Starts   Min   90s
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                 13  1198  13.3
                                  Bukayo Saka               20  1729  19.2
                                  David Raya                38  3420  38.0
                                  Declan Rice               33  2825  31.4
                                  Ethan Nwaneri             11   895   9.9
                                  Gabriel Jesus              6   608   6.8
                                  Gabriel Magalhães         28  2363  26.3
                                  Gabriel Martinelli        25  2290  25.4
                                  Jakub Kiwior              10  1122  12.5
                                  Jorginho                   9   704   7.8
                                  Jurriën Timber            27  2417  26.9
                                  Kai Havertz               21  1875  20.8
                                  Kieran Tierney             2   259   2.9
                                  Leandro Trossard          28  2546  28.3
                                  Martin Ødegaard           26  2325  25.8
                                  Mikel Merino              17  1586  17.6
                                  Myles Lewis-Skelly        15  1369  15.2
                                  Nathan Butler-Oyedeji      0     7   0.1
                                  Oleksandr Zinchenko        5   527   5.9
                                  Raheem Sterling            7   499   5.5

                                                        Performance      ...  \
                                                                Gls Ast  ...
league             season team    player                                 ...
ENG-Premier League 2425   Arsenal Ben White                       0   2  ...
                                  Bukayo Saka                     6  10  ...
                                  David Raya                      0   0  ...
                                  Declan Rice                     4   7  ...
                                  Ethan Nwaneri                   4   2  ...
                                  Gabriel Jesus                   3   0  ...
                                  Gabriel Magalhães               3   1  ...
                                  Gabriel Martinelli              8   4  ...
                                  Jakub Kiwior                    1   0  ...
                                  Jorginho                        0   0  ...
                                  Jurriën Timber                  1   3  ...
                                  Kai Havertz                     9   3  ...
                                  Kieran Tierney                  1   0  ...
                                  Leandro Trossard                8   7  ...
                                  Martin Ødegaard                 3   8  ...
                                  Mikel Merino                    7   2  ...
                                  Myles Lewis-Skelly              1   0  ...
                                  Nathan Butler-Oyedeji           0   0  ...
                                  Oleksandr Zinchenko             0   1  ...
                                  Raheem Sterling                 0   2  ...

                                                                            \
                                                        G-PK PK PKatt CrdY
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                0  0     0    2
                                  Bukayo Saka              5  1     1    3
                                  David Raya               0  0     0    3
                                  Declan Rice              4  0     0    7
                                  Ethan Nwaneri            4  0     0    1
                                  Gabriel Jesus            3  0     0    4
                                  Gabriel Magalhães        3  0     0    4
                                  Gabriel Martinelli       8  0     0    1
                                  Jakub Kiwior             1  0     0    1
                                  Jorginho                 0  0     0    5
                                  Jurriën Timber           1  0     0    7
                                  Kai Havertz              9  0     0    5
                                  Kieran Tierney           1  0     0    0
                                  Leandro Trossard         8  0     0    4
                                  Martin Ødegaard          2  1     1    4
                                  Mikel Merino             7  0     0    4
                                  Myles Lewis-Skelly       1  0     0    3
                                  Nathan Butler-Oyedeji    0  0     0    0
                                  Oleksandr Zinchenko      0  0     0    1
                                  Raheem Sterling          0  0     0    1

                                                             Per 90 Minutes  \
                                                        CrdR            Gls
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                0            0.0
                                  Bukayo Saka              0           0.31
                                  David Raya               0            0.0
                                  Declan Rice              1           0.13
                                  Ethan Nwaneri            0            0.4
                                  Gabriel Jesus            0           0.44
                                  Gabriel Magalhães        0           0.11
                                  Gabriel Martinelli       0           0.31
                                  Jakub Kiwior             0           0.08
                                  Jorginho                 0            0.0
                                  Jurriën Timber           0           0.04
                                  Kai Havertz              0           0.43
                                  Kieran Tierney           0           0.35
                                  Leandro Trossard         1           0.28
                                  Martin Ødegaard          0           0.12
                                  Mikel Merino             1            0.4
                                  Myles Lewis-Skelly       2           0.07
                                  Nathan Butler-Oyedeji    0            0.0
                                  Oleksandr Zinchenko      0            0.0
                                  Raheem Sterling          0            0.0

                                                                           \
                                                          Ast   G+A  G-PK
league             season team    player
ENG-Premier League 2425   Arsenal Ben White              0.15  0.15   0.0
                                  Bukayo Saka            0.52  0.83  0.26
                                  David Raya              0.0   0.0   0.0
                                  Declan Rice            0.22  0.35  0.13
                                  Ethan Nwaneri           0.2   0.6   0.4
                                  Gabriel Jesus           0.0  0.44  0.44
                                  Gabriel Magalhães      0.04  0.15  0.11
                                  Gabriel Martinelli     0.16  0.47  0.31
                                  Jakub Kiwior            0.0  0.08  0.08
                                  Jorginho                0.0   0.0   0.0
                                  Jurriën Timber         0.11  0.15  0.04
                                  Kai Havertz            0.14  0.58  0.43
                                  Kieran Tierney          0.0  0.35  0.35
                                  Leandro Trossard       0.25  0.53  0.28
                                  Martin Ødegaard        0.31  0.43  0.08
                                  Mikel Merino           0.11  0.51   0.4
                                  Myles Lewis-Skelly      0.0  0.07  0.07
                                  Nathan Butler-Oyedeji   0.0   0.0   0.0
                                  Oleksandr Zinchenko    0.17  0.17   0.0
                                  Raheem Sterling        0.36  0.36   0.0


                                                        G+A-PK
league             season team    player
ENG-Premier League 2425   Arsenal Ben White               0.15
                                  Bukayo Saka             0.78
                                  David Raya               0.0
                                  Declan Rice             0.35
                                  Ethan Nwaneri            0.6
                                  Gabriel Jesus           0.44
                                  Gabriel Magalhães       0.15
                                  Gabriel Martinelli      0.47
                                  Jakub Kiwior            0.08
                                  Jorginho                 0.0
                                  Jurriën Timber          0.15
                                  Kai Havertz             0.58
                                  Kieran Tierney          0.35
                                  Leandro Trossard        0.53
                                  Martin Ødegaard         0.39
                                  Mikel Merino            0.51
                                  Myles Lewis-Skelly      0.07
                                  Nathan Butler-Oyedeji    0.0
                                  Oleksandr Zinchenko     0.17
                                  Raheem Sterling         0.36

[20 rows x 21 columns]

<br>
<br>
<< Data structure Analysis >>
<br>

In [2]:
import soccerdata as sd

fbref = sd.FBref(leagues="ENG-Premier League", seasons="2024-2025")
df = fbref.read_player_season_stats(stat_type="standard")

print(df.shape)          # # of rows and columns
print(df.index.names)    # index structure - player names may be included here
print(df.columns.tolist())  # Column list — check where goals, assists, xG are located
df.head()

[07/06/26 15:55:32] INFO     Saving cached data to /Users/jade/soccerdata/data/FBref                 ]8;id=3479969;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=3479970;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\

(574, 21)
['league', 'season', 'team', 'player']
[('nation', ''), ('pos', ''), ('age', ''), ('born', ''), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK')]

                                                nation    pos age  born  \

league             season team    player
ENG-Premier League 2425   Arsenal Ben White        ENG     DF  26  1997
                                  Bukayo Saka      ENG  FW,MF  22  2001
                                  David Raya       ESP     GK  28  1995
                                  Declan Rice      ENG     MF  25  1999
                                  Ethan Nwaneri    ENG  FW,MF  17  2007

                                                Playing Time               \
                                                          MP Starts   Min
league             season team    player
ENG-Premier League 2425   Arsenal Ben White               17     13  1198
                                  Bukayo Saka             25     20  1729
                                  David Raya              38     38  3420
                                  Declan Rice             35     33  2825
                                  Ethan Nwaneri           26     11   895

                                                      Performance      ...  \
                                                  90s         Gls Ast  ...
league             season team    player                               ...
ENG-Premier League 2425   Arsenal Ben White      13.3           0   2  ...
                                  Bukayo Saka    19.2           6  10  ...
                                  David Raya     38.0           0   0  ...
                                  Declan Rice    31.4           4   7  ...
                                  Ethan Nwaneri   9.9           4   2  ...

                                                                         \
                                                G-PK PK PKatt CrdY CrdR
league             season team    player
ENG-Premier League 2425   Arsenal Ben White        0  0     0    2    0
                                  Bukayo Saka      5  1     1    3    0
                                  David Raya       0  0     0    3    0
                                  Declan Rice      4  0     0    7    1
                                  Ethan Nwaneri    4  0     0    1    0

                                                Per 90 Minutes              \
                                                           Gls   Ast   G+A
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                0.0  0.15  0.15
                                  Bukayo Saka             0.31  0.52  0.83
                                  David Raya               0.0   0.0   0.0
                                  Declan Rice             0.13  0.22  0.35
                                  Ethan Nwaneri            0.4   0.2   0.6


                                                 G-PK G+A-PK
league             season team    player
ENG-Premier League 2425   Arsenal Ben White       0.0   0.15
                                  Bukayo Saka    0.26   0.78
                                  David Raya      0.0    0.0
                                  Declan Rice    0.13   0.35
                                  Ethan Nwaneri   0.4    0.6

[5 rows x 21 columns]

<br>
<br>
<br>

In [3]:
def get_player_stats(name, season="2425", competition="ENG-Premier League"):
    # 1. Filter by season first
    try:
        rows = df.xs(season, level="season")
    except KeyError:
        return {"error": f"No data for season {season}"}

    # 2. Search by name — strict match first, then fall back to looser matches
    all_players = rows.index.get_level_values("player").unique()

    # Step 1: whole-word match (treat hyphens as spaces)
    matches = [p for p in all_players
               if name.lower() in p.lower().replace("-", " ").split()]

    # Step 2: if nothing found, try substring match
    if not matches:
        matches = [p for p in all_players if name.lower() in p.lower()]

    # Step 3: if still nothing, compare with hyphens/spaces removed
    # (e.g. "heungmin" matches "sonheungmin")
    if not matches:
        squash = lambda s: s.lower().replace("-", "").replace(" ", "")
        matches = [p for p in all_players if squash(name) in squash(p)]

    # Final safety net — return an error dict instead of crashing
    if not matches:
        return {"error": f"Player '{name}' not found"}
    if len(matches) > 1:
        return {"error": "Multiple players matched — please be more specific",
                "candidates": matches}

    # 3. Return one record per team — do NOT merge rows
    # (a mid-season transfer means two rows; keep them separate
    #  so the Judge can verify numbers against the original data)
    player_name = matches[0]
    player_rows = rows.xs(player_name, level="player")
    records = []
    for idx, row in player_rows.iterrows():
        team = idx[-1] if isinstance(idx, tuple) else idx  # if tuple, take the last part (team)
        stats = {f"{c[0]}_{c[1]}" if c[1] else c[0]: v for c, v in row.items()}
        records.append({"team": team, "stats": stats})

    return {
        "player": player_name,
        "season": season,
        "competition": competition,
        "records": records,  # length 1 for one team, 2+ if transferred mid-season
    }

In [4]:
print(get_player_stats("Saka"))

{'player': 'Bukayo Saka', 'season': '2425', 'competition': 'ENG-Premier League', 'records': [{'team': 'Arsenal', 'stats': {'nation': 'ENG', 'pos': 'FW,MF', 'age': 22, 'born': 2001, 'Playing Time_MP': 25, 'Playing Time_Starts': 20, 'Playing Time_Min': 1729, 'Playing Time_90s': 19.2, 'Performance_Gls': 6, 'Performance_Ast': 10, 'Performance_G+A': 16, 'Performance_G-PK': 5, 'Performance_PK': 1, 'Performance_PKatt': 1, 'Performance_CrdY': 3, 'Performance_CrdR': 0, 'Per 90 Minutes_Gls': 0.31, 'Per 90 Minutes_Ast': 0.52, 'Per 90 Minutes_G+A': 0.83, 'Per 90 Minutes_G-PK': 0.26, 'Per 90 Minutes_G+A-PK': 0.78}}]}

In [5]:
get_player_stats("Bissaka")    # → Wan-Bissaka 잡혀야 함

{'player': 'Aaron Wan-Bissaka',
 'season': '2425',
 'competition': 'ENG-Premier League',
 'records': [{'team': 'West Ham',
   'stats': {'nation': 'COD',
    'pos': 'DF,MF',
    'age': 26,
    'born': 1997,
    'Playing Time_MP': 36,
    'Playing Time_Starts': 35,
    'Playing Time_Min': 3154,
    'Playing Time_90s': 35.0,
    'Performance_Gls': 2,
    'Performance_Ast': 5,
    'Performance_G+A': 7,
    'Performance_G-PK': 2,
    'Performance_PK': 0,
    'Performance_PKatt': 0,
    'Performance_CrdY': 1,
    'Performance_CrdR': 0,
    'Per 90 Minutes_Gls': 0.06,
    'Per 90 Minutes_Ast': 0.14,
    'Per 90 Minutes_G+A': 0.2,
    'Per 90 Minutes_G-PK': 0.06,
    'Per 90 Minutes_G+A-PK': 0.2}}]}

In [6]:
get_player_stats("Silva")      # more than one candidates

{'error': 'Multiple players matched — please be more specific',
 'candidates': ['Bernardo Silva', 'Eric da Silva Moreira', 'Jota Silva']}

In [7]:
get_player_stats("Son")

{'player': 'Son Heung-min',
 'season': '2425',
 'competition': 'ENG-Premier League',
 'records': [{'team': 'Tottenham',
   'stats': {'nation': 'KOR',
    'pos': 'FW,MF',
    'age': 32,
    'born': 1992,
    'Playing Time_MP': 30,
    'Playing Time_Starts': 24,
    'Playing Time_Min': 2110,
    'Playing Time_90s': 23.4,
    'Performance_Gls': 7,
    'Performance_Ast': 9,
    'Performance_G+A': 16,
    'Performance_G-PK': 6,
    'Performance_PK': 1,
    'Performance_PKatt': 2,
    'Performance_CrdY': 1,
    'Performance_CrdR': 0,
    'Per 90 Minutes_Gls': 0.3,
    'Per 90 Minutes_Ast': 0.38,
    'Per 90 Minutes_G+A': 0.68,
    'Per 90 Minutes_G-PK': 0.26,
    'Per 90 Minutes_G+A-PK': 0.64}}]}

In [8]:
get_player_stats("heungmin")

{'player': 'Son Heung-min',
 'season': '2425',
 'competition': 'ENG-Premier League',
 'records': [{'team': 'Tottenham',
   'stats': {'nation': 'KOR',
    'pos': 'FW,MF',
    'age': 32,
    'born': 1992,
    'Playing Time_MP': 30,
    'Playing Time_Starts': 24,
    'Playing Time_Min': 2110,
    'Playing Time_90s': 23.4,
    'Performance_Gls': 7,
    'Performance_Ast': 9,
    'Performance_G+A': 16,
    'Performance_G-PK': 6,
    'Performance_PK': 1,
    'Performance_PKatt': 2,
    'Performance_CrdY': 1,
    'Performance_CrdR': 0,
    'Per 90 Minutes_Gls': 0.3,
    'Per 90 Minutes_Ast': 0.38,
    'Per 90 Minutes_G+A': 0.68,
    'Per 90 Minutes_G-PK': 0.26,
    'Per 90 Minutes_G+A-PK': 0.64}}]}

In [9]:
get_player_stats("zzzzz")

{'error': "Player 'zzzzz' not found"}

In [10]:
import json
print(json.dumps(get_player_stats("Saka"), indent=2, ensure_ascii=False))

{
  "player": "Bukayo Saka",
  "season": "2425",
  "competition": "ENG-Premier League",
  "records": [
    {
      "team": "Arsenal",
      "stats": {
        "nation": "ENG",
        "pos": "FW,MF",
        "age": 22,
        "born": 2001,
        "Playing Time_MP": 25,
        "Playing Time_Starts": 20,
        "Playing Time_Min": 1729,
        "Playing Time_90s": 19.2,
        "Performance_Gls": 6,
        "Performance_Ast": 10,
        "Performance_G+A": 16,
        "Performance_G-PK": 5,
        "Performance_PK": 1,
        "Performance_PKatt": 1,
        "Performance_CrdY": 3,
        "Performance_CrdR": 0,
        "Per 90 Minutes_Gls": 0.31,
        "Per 90 Minutes_Ast": 0.52,
        "Per 90 Minutes_G+A": 0.83,
        "Per 90 Minutes_G-PK": 0.26,
        "Per 90 Minutes_G+A-PK": 0.78
      }
    }
  ]
}

In [11]:
# Find players transferred mid-season

get_player_stats("Rashford")

{'player': 'Marcus Rashford',
 'season': '2425',
 'competition': 'ENG-Premier League',
 'records': [{'team': 'Aston Villa',
   'stats': {'nation': 'ENG',
    'pos': 'FW,MF',
    'age': 26,
    'born': 1997,
    'Playing Time_MP': 10,
    'Playing Time_Starts': 4,
    'Playing Time_Min': 444,
    'Playing Time_90s': 4.9,
    'Performance_Gls': 2,
    'Performance_Ast': 2,
    'Performance_G+A': 4,
    'Performance_G-PK': 1,
    'Performance_PK': 1,
    'Performance_PKatt': 1,
    'Performance_CrdY': 0,
    'Performance_CrdR': 0,
    'Per 90 Minutes_Gls': 0.41,
    'Per 90 Minutes_Ast': 0.41,
    'Per 90 Minutes_G+A': 0.81,
    'Per 90 Minutes_G-PK': 0.2,
    'Per 90 Minutes_G+A-PK': 0.61}},
  {'team': 'Manchester Utd',
   'stats': {'nation': 'ENG',
    'pos': 'MF',
    'age': 26,
    'born': 1997,
    'Playing Time_MP': 15,
    'Playing Time_Starts': 12,
    'Playing Time_Min': 978,
    'Playing Time_90s': 10.9,
    'Performance_Gls': 4,
    'Performance_Ast': 1,
    'Performance_G+A': 5,
    'Performance_G-PK': 4,
    'Performance_PK': 0,
    'Performance_PKatt': 0,
    'Performance_CrdY': 2,
    'Performance_CrdR': 0,
    'Per 90 Minutes_Gls': 0.37,
    'Per 90 Minutes_Ast': 0.09,
    'Per 90 Minutes_G+A': 0.46,
    'Per 90 Minutes_G-PK': 0.37,
    'Per 90 Minutes_G+A-PK': 0.46}}]}

In [13]:
import sys
sys.path.append("..")

from data.loader import get_player_stats
get_player_stats("Rashford")

[07/06/26 16:18:17] INFO     Saving cached data to /Users/jade/soccerdata/data/FBref                 ]8;id=3479975;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=3479976;file:///Users/jade/Project/AI-Football-Scout/venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\

{'player': 'Marcus Rashford',
 'season': '2425',
 'competition': 'ENG-Premier League',
 'records': [{'team': 'Aston Villa',
   'stats': {'nation': 'ENG',
    'pos': 'FW,MF',
    'age': 26,
    'born': 1997,
    'Playing Time_MP': 10,
    'Playing Time_Starts': 4,
    'Playing Time_Min': 444,
    'Playing Time_90s': 4.9,
    'Performance_Gls': 2,
    'Performance_Ast': 2,
    'Performance_G+A': 4,
    'Performance_G-PK': 1,
    'Performance_PK': 1,
    'Performance_PKatt': 1,
    'Performance_CrdY': 0,
    'Performance_CrdR': 0,
    'Per 90 Minutes_Gls': 0.41,
    'Per 90 Minutes_Ast': 0.41,
    'Per 90 Minutes_G+A': 0.81,
    'Per 90 Minutes_G-PK': 0.2,
    'Per 90 Minutes_G+A-PK': 0.61}},
  {'team': 'Manchester Utd',
   'stats': {'nation': 'ENG',
    'pos': 'MF',
    'age': 26,
    'born': 1997,
    'Playing Time_MP': 15,
    'Playing Time_Starts': 12,
    'Playing Time_Min': 978,
    'Playing Time_90s': 10.9,
    'Performance_Gls': 4,
    'Performance_Ast': 1,
    'Performance_G+A': 5,
    'Performance_G-PK': 4,
    'Performance_PK': 0,
    'Performance_PKatt': 0,
    'Performance_CrdY': 2,
    'Performance_CrdR': 0,
    'Per 90 Minutes_Gls': 0.37,
    'Per 90 Minutes_Ast': 0.09,
    'Per 90 Minutes_G+A': 0.46,
    'Per 90 Minutes_G-PK': 0.37,
    'Per 90 Minutes_G+A-PK': 0.46}}]}

In [14]:
get_player_stats("Silva")

{'error': 'Multiple players matched — please be more specific',
 'candidates': ['Bernardo Silva', 'Eric da Silva Moreira', 'Jota Silva']}